apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalwire-ai-agent
  labels:
    app: signalwire-ai-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: signalwire-ai-agent
  template:
    metadata:
      labels:
        app: signalwire-ai-agent
    spec:
      containers:
      - name: ai-agent
        image: signalwire/ai-agent:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        - name: SWML_BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: agent-auth
              key: username
        - name: SWML_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: agent-auth
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: signalwire-ai-agent-service
  labels:
    app: signalwire-ai-agent
spec:
  selector:
    app: signalwire-ai-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-auth
type: Opaque
data:
  # Base64 encoded credentials (change these!)
  username: YWdlbnQ=  # "agent"
  password: c2VjdXJlX3Bhc3N3b3Jk  # "secure_password" 